export const EDIT_PATIENT_PROFILE="EDIT_PATIENT_PROFILE";
export const GET_PROFILE_DATA="GET_PROFILE_DATA";
export const ADD_MEDICAL_HISTORY_DATA="ADD_MEDICAL_HISTORY_DATA";
export const VIEW_MEDICAL_HISTORY_DATA ="VIEW_MEDICAL_HISTORY_DATA";
