export const EDIT_ThERAPIST_PROFILE="EDIT_ThERAPIST_PROFILE";
export const GET_PROFILE_DATA="GET_PROFILE_DATA";
export const GET_ALL_THERAPISTS="GET_ALL_THERAPISTS";
export const GET_ALL_APPOINTMENTS ="GET_ALL_APPOINTMENTS";
export const GET_APPOINTMENT="GET_APPOINTMENT"
export const DELETE_APPOINTMENT="DELETE_APPOINTMENT"
